def Content():
    TOPIC_DICT = {"Basics":[["Accuracy and Alignment","Accurately unpacking the standard–-not oversimplifying it, nor making it more complex than it has to be. Making sense of what the standard says, and understanding exactly what the student needs to know and be able to do to get there.","/https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267518//","/static/images/1.jpeg"],
                            ["Qualitative Analysis","Qualitative Analysis in terms of being able to read a variety of texts both critically and holistically. To be able to decode grade level texts of appropriate complexity, and to then be able to take that text apart in terms of ideas, evidence, theme, and craft.","/https://www.investopedia.com/terms/q/qualitativeanalysis.asp/","/static/images/2.jpeg"],
                            ["Data Forms and Quality","Data as in, units, lessons, and activities are designed to flexibly respond to that data in authentic ways without leaving it all on the teacher’s shoulders to do so on the fly–or, worse, at the local “data team” meeting.","/https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0035087/","/static/images/3.jpeg"],
                            ["Instructional Design","There are countless factors in the academic achievement of a student, few are more powerful than instructional design.","/https://en.wikipedia.org/wiki/Instructional_design/","/static/images/4.jpeg"],
                            ["Depth of Knowledge","Self-initiated transfer is a key indicator of understanding. It can be defined here as the ability to transfer knowledge or skill to a new and unfamiliar context, preferably unprompted. Put another way, students who know what to use what knowledge, when without being told to do so.","/https://www.thoughtco.com/how-depth-of-knowledge-drives-learning-and-assessment-3194253/","/static/images/5.jpeg"],
                            ["Student Motivation","Student effort as in, supporting students emotionally, metacognitively, and intellectually to give themselves to the process of mastering academic content.","/https://www.google.com/search?q=student+motivation&client=firefox-b-d&sxsrf=ACYBGNQsAkyZkUL3QyMj1OsAaTrNs9g0Gw:1571552163851&source=lnms&tbm=vid&sa=X&ved=0ahUKEwiqrOODmKrlAhVQ8HMBHZxqBlIQ_AUIEigC&biw=1366&bih=626/","/static/images/6.jpeg"]],
                  "Web_Dev":[["Accuracy and Alignment","Accurately unpacking the standard–-not oversimplifying it, nor making it more complex than it has to be. Making sense of what the standard says, and understanding exactly what the student needs to know and be able to do to get there.","/https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267518//","/static/images/1.jpeg"],
                            ["Qualitative Analysis","Qualitative Analysis in terms of being able to read a variety of texts both critically and holistically. To be able to decode grade level texts of appropriate complexity, and to then be able to take that text apart in terms of ideas, evidence, theme, and craft.","/https://www.investopedia.com/terms/q/qualitativeanalysis.asp/","/static/images/2.jpeg"],
                            ["Data Forms and Quality","Data as in, units, lessons, and activities are designed to flexibly respond to that data in authentic ways without leaving it all on the teacher’s shoulders to do so on the fly–or, worse, at the local “data team” meeting.","/https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0035087/","/static/images/3.jpeg"],
                            ["Instructional Design","There are countless factors in the academic achievement of a student, few are more powerful than instructional design.","/https://en.wikipedia.org/wiki/Instructional_design/","/static/images/4.jpeg"],
                            ["Depth of Knowledge","Self-initiated transfer is a key indicator of understanding. It can be defined here as the ability to transfer knowledge or skill to a new and unfamiliar context, preferably unprompted. Put another way, students who know what to use what knowledge, when without being told to do so.","/https://www.thoughtco.com/how-depth-of-knowledge-drives-learning-and-assessment-3194253/","/static/images/5.jpeg"],
                             ["Student Motivation","Student effort as in, supporting students emotionally, metacognitively, and intellectually to give themselves to the process of mastering academic content.","/https://www.google.com/search?q=student+motivation&client=firefox-b-d&sxsrf=ACYBGNQsAkyZkUL3QyMj1OsAaTrNs9g0Gw:1571552163851&source=lnms&tbm=vid&sa=X&ved=0ahUKEwiqrOODmKrlAhVQ8HMBHZxqBlIQ_AUIEigC&biw=1366&bih=626/","/static/images/6.jpeg"]],
                  "android":[["Accuracy and Alignment","Accurately unpacking the standard–-not oversimplifying it, nor making it more complex than it has to be. Making sense of what the standard says, and understanding exactly what the student needs to know and be able to do to get there.","/https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267518//","/static/images/1.jpeg"],
                            ["Qualitative Analysis","Qualitative Analysis in terms of being able to read a variety of texts both critically and holistically. To be able to decode grade level texts of appropriate complexity, and to then be able to take that text apart in terms of ideas, evidence, theme, and craft.","/https://www.investopedia.com/terms/q/qualitativeanalysis.asp/","/static/images/2.jpeg"],
                            ["Data Forms and Quality","Data as in, units, lessons, and activities are designed to flexibly respond to that data in authentic ways without leaving it all on the teacher’s shoulders to do so on the fly–or, worse, at the local “data team” meeting.","/https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0035087/","/static/images/3.jpeg"],
                            ["Instructional Design","There are countless factors in the academic achievement of a student, few are more powerful than instructional design.","/https://en.wikipedia.org/wiki/Instructional_design/","/static/images/4.jpeg"],
                            ["Depth of Knowledge","Self-initiated transfer is a key indicator of understanding. It can be defined here as the ability to transfer knowledge or skill to a new and unfamiliar context, preferably unprompted. Put another way, students who know what to use what knowledge, when without being told to do so.","/https://www.thoughtco.com/how-depth-of-knowledge-drives-learning-and-assessment-3194253/","/static/images/5.jpeg"],
                             ["Student Motivation","Student effort as in, supporting students emotionally, metacognitively, and intellectually to give themselves to the process of mastering academic content.","/https://www.google.com/search?q=student+motivation&client=firefox-b-d&sxsrf=ACYBGNQsAkyZkUL3QyMj1OsAaTrNs9g0Gw:1571552163851&source=lnms&tbm=vid&sa=X&ved=0ahUKEwiqrOODmKrlAhVQ8HMBHZxqBlIQ_AUIEigC&biw=1366&bih=626/","/static/images/6.jpeg"]]
                  }

    return TOPIC_DICT
